### ISSUE TITLE
Add support for crystal

### ISSUE THREAD

**Issue by waghanza** [inch-ci/inch_ci-web#227] opened 2018-08-09 10:16 UTC
Hi,

[crystal](http://crystal-lang.org) syntax is closed to `ruby` (documentation as well).

It could be enjoyable to have support for `crystal`.

Documentation is **rdoc** like.

Regards,

**Comment by nschonni** [comment] 2018-08-09 12:55
Duplicate of #147

**Closed** 2018-08-17 17:51 UTC
