### ISSUE TITLE
Add support for Go

### ISSUE THREAD

**Issue by dtoubelis** [inch-ci/inch_ci-web#181] opened 2017-03-06 13:49 UTC
I like your idea. It would be nice to have support for Go. Go already has documentation tools, so it should be relatively straightforward to integrate them in this project.

**Comment by rrrene** [comment] 2017-03-07 13:27
Thx for your kind words. I will close this, as it is a duplicate of #128 :+1:

**Closed by rrrene** 2017-03-07 13:27 UTC
