### ISSUE TITLE
Add support for python

### ISSUE THREAD

**Issue by vonpupp** [inch-ci/inch_ci-web#169] opened 2017-01-13 22:20 UTC
Hello,

I was wondering if you could please add support to python.

Thank you very much.

**Comment by rrrene** [comment] 2017-01-14 17:17
There seems to be the occansional interest, but it is not high up on my list. PRs/companion projects are always welcome though! :+1:

I'm closing this issue, since it is a duplicate of #156.

**Closed by rrrene** 2017-01-14 17:17 UTC
